import { Recipe } from './types';

const allRecipes: Recipe[] = [
  {
    id: 'quinoa-avocado-salad',
    name: 'Quinoa Avocado Salad',
    category: 'salads',
    image: 'quinoa-salad',
    description:
      'A refreshing and nutritious salad with quinoa, avocado, and a zesty lime dressing. Perfect for a light lunch.',
    calories: 350,
    protein: 12,
    carbs: 40,
    fat: 18,
    ingredients: [
      '1 cup cooked quinoa',
      '1 ripe avocado, diced',
      '1 cup cherry tomatoes, halved',
      '1/2 cucumber, diced',
      '1/4 red onion, finely chopped',
      '1/4 cup chopped cilantro',
      'Juice of 1 lime',
      '2 tbsp olive oil',
    ],
    instructions: [
      'In a large bowl, combine the cooked quinoa, avocado, cherry tomatoes, cucumber, and red onion.',
      'In a small bowl, whisk together the lime juice and olive oil.',
      'Pour the dressing over the salad and toss to combine.',
      'Stir in the cilantro just before serving.',
    ],
  },
  {
    id: 'grilled-chicken-breast',
    name: 'Herbed Grilled Chicken',
    category: 'chicken',
    image: 'grilled-chicken-breast',
    description:
      'Juicy and flavorful grilled chicken breast marinated in herbs and lemon. A versatile protein for any meal.',
    calories: 280,
    protein: 45,
    carbs: 2,
    fat: 10,
    ingredients: [
      '2 boneless, skinless chicken breasts',
      '2 tbsp olive oil',
      '1 lemon, juiced',
      '1 tsp dried oregano',
      '1 tsp dried thyme',
      '2 cloves garlic, minced',
    ],
    instructions: [
      'In a bowl, mix olive oil, lemon juice, oregano, thyme, and garlic.',
      'Add chicken breasts and marinate for at least 30 minutes.',
      'Preheat grill to medium-high heat.',
      'Grill chicken for 6-8 minutes per side, or until cooked through.',
    ],
  },
  {
    id: 'baked-salmon-with-asparagus',
    name: 'Baked Salmon & Asparagus',
    category: 'fish-seafood',
    image: 'salmon-asparagus',
    description:
      'A simple and elegant one-pan meal of tender baked salmon and crisp asparagus. Rich in omega-3s.',
    calories: 420,
    protein: 35,
    carbs: 10,
    fat: 28,
    ingredients: [
      '2 salmon fillets',
      '1 bunch asparagus, trimmed',
      '1 tbsp olive oil',
      '1 lemon, sliced',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Place salmon and asparagus on a baking sheet.',
      'Drizzle with olive oil, season with salt and pepper.',
      'Top salmon with lemon slices.',
      'Bake for 12-15 minutes, or until salmon is cooked through.',
    ],
  },
  {
    id: 'hearty-lentil-soup',
    name: 'Hearty Lentil Soup',
    category: 'vegetarian',
    image: 'lentil-soup',
    description:
      'A warm and comforting lentil soup packed with vegetables and flavor. A satisfying and high-fiber vegetarian meal.',
    calories: 300,
    protein: 18,
    carbs: 50,
    fat: 4,
    ingredients: [
      '1 cup brown or green lentils, rinsed',
      '1 onion, chopped',
      '2 carrots, chopped',
      '2 celery stalks, chopped',
      '4 cups vegetable broth',
      '1 tsp cumin',
    ],
    instructions: [
      'In a large pot, sauté onion, carrots, and celery until softened.',
      'Add lentils, vegetable broth, and cumin.',
      'Bring to a boil, then simmer for 25-30 minutes until lentils are tender.',
      'Season with salt and pepper to taste.',
    ],
  },
  {
    id: 'avocado-toast-with-egg',
    name: 'Avocado Toast with Egg',
    category: 'low-calorie',
    image: 'avocado-toast',
    description:
      'A quick and easy breakfast or snack. Creamy avocado on whole-grain toast, topped with an egg for extra protein.',
    calories: 250,
    protein: 14,
    carbs: 20,
    fat: 15,
    ingredients: [
      '1 slice whole-grain bread, toasted',
      '1/2 avocado',
      '1 large egg',
      'Red pepper flakes (optional)',
    ],
    instructions: [
      'Mash the avocado and spread it on the toast.',
      'Cook the egg to your liking (fried, poached, or scrambled).',
      'Place the egg on top of the avocado toast.',
      'Sprinkle with red pepper flakes if desired.',
    ],
  },
  {
    id: 'berry-blast-smoothie',
    name: 'Berry Blast Smoothie',
    category: 'smoothies',
    isCocktail: false,
    image: 'berry-smoothie',
    description:
      'A refreshing smoothie loaded with antioxidants from mixed berries and protein from Greek yogurt.',
    calories: 220,
    protein: 15,
    carbs: 30,
    fat: 5,
    ingredients: [
      '1 cup mixed berries (frozen)',
      '1/2 cup Greek yogurt',
      '1/2 cup unsweetened almond milk',
      '1 tbsp chia seeds',
    ],
    instructions: [
      'Combine all ingredients in a blender.',
      'Blend until smooth.',
      'Pour into a glass and enjoy immediately.',
    ],
  },
  {
    id: 'chicken-veggie-stir-fry',
    name: 'Chicken & Veggie Stir-fry',
    category: 'chicken',
    image: 'chicken-stir-fry',
    description:
      'A quick, colorful, and healthy stir-fry with tender chicken and crisp vegetables in a light soy-ginger sauce.',
    calories: 380,
    protein: 30,
    carbs: 25,
    fat: 18,
    ingredients: [
      '1 chicken breast, thinly sliced',
      '1 cup broccoli florets',
      '1 bell pepper, sliced',
      '1 carrot, julienned',
      '2 tbsp soy sauce',
      '1 tsp grated ginger',
    ],
    instructions: [
      'In a wok or large skillet, stir-fry chicken until cooked.',
      'Add broccoli, bell pepper, and carrot. Stir-fry for 3-5 minutes.',
      'Add soy sauce and ginger, and toss everything to combine.',
      'Serve hot, optionally with brown rice.',
    ],
  },
  {
    id: 'classic-greek-salad',
    name: 'Classic Greek Salad',
    category: 'salads',
    image: 'greek-salad',
    description:
      'A timeless salad with crisp lettuce, juicy tomatoes, cucumbers, olives, and feta cheese in a simple vinaigrette.',
    calories: 320,
    protein: 8,
    carbs: 15,
    fat: 25,
    ingredients: [
      '1 head of romaine lettuce, chopped',
      '1 cup cherry tomatoes, halved',
      '1 cucumber, sliced',
      '1/2 cup Kalamata olives',
      '1/2 cup feta cheese, crumbled',
      '3 tbsp olive oil',
      '1 tbsp red wine vinegar',
    ],
    instructions: [
      'Combine lettuce, tomatoes, cucumber, olives, and feta in a large bowl.',
      'In a small bowl, whisk together olive oil and red wine vinegar.',
      'Drizzle dressing over the salad and toss to serve.',
    ],
  },
  {
    id: 'garlic-shrimp-zoodles',
    name: 'Garlic Shrimp with Zoodles',
    category: 'fish-seafood',
    image: 'shrimp-scampi',
    description:
      'A light, low-carb alternative to pasta. Sautéed garlic shrimp served over spiralized zucchini noodles.',
    calories: 290,
    protein: 25,
    carbs: 12,
    fat: 18,
    ingredients: [
      '1 lb shrimp, peeled and deveined',
      '2 medium zucchinis, spiralized',
      '3 cloves garlic, minced',
      '2 tbsp olive oil',
      'Juice of 1/2 lemon',
      'Pinch of red pepper flakes',
    ],
    instructions: [
      'In a large skillet, heat olive oil over medium heat. Add garlic and red pepper flakes, and cook for 1 minute.',
      'Add shrimp and cook until pink, about 2-3 minutes per side.',
      'Add zucchini noodles (zoodles) to the skillet and toss with the shrimp.',
      'Cook for another 1-2 minutes until zoodles are slightly tender.',
      'Squeeze lemon juice over the top before serving.',
    ],
  },
  {
    id: 'veggie-tofu-scramble',
    name: 'Veggie Tofu Scramble',
    category: 'vegetarian',
    image: 'tofu-scramble',
    description:
      'A delicious and protein-rich vegan breakfast that mimics scrambled eggs using tofu and your favorite vegetables.',
    calories: 260,
    protein: 20,
    carbs: 10,
    fat: 16,
    ingredients: [
      '1 block firm tofu, pressed and crumbled',
      '1/2 onion, chopped',
      '1 bell pepper, chopped',
      '1 cup spinach',
      '1 tsp turmeric',
      '1 tbsp nutritional yeast',
    ],
    instructions: [
      'In a skillet, sauté onion and bell pepper until soft.',
      'Add crumbled tofu, turmeric, and nutritional yeast. Cook, stirring, for 5 minutes.',
      'Stir in spinach and cook until wilted.',
      'Season with salt and pepper to taste.',
    ],
  },
  {
    id: 'mediterranean-roasted-vegetables',
    name: 'Mediterranean Roasted Vegetables',
    category: 'vegetable',
    image: 'roasted-vegetables',
    description:
      'A simple, flavorful side dish of colorful vegetables roasted with olive oil and Mediterranean herbs.',
    calories: 180,
    protein: 4,
    carbs: 20,
    fat: 10,
    ingredients: [
      '1 zucchini, chopped',
      '1 red bell pepper, chopped',
      '1 red onion, cut into wedges',
      '1 cup cherry tomatoes',
      '2 tbsp olive oil',
      '1 tsp dried oregano',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Toss all vegetables with olive oil and oregano on a baking sheet.',
      'Season with salt and pepper.',
      'Roast for 20-25 minutes, until tender and slightly caramelized.',
    ],
  },
  {
    id: 'chocolate-avocado-mousse',
    name: 'Chocolate Avocado Mousse',
    category: 'desserts',
    isDessert: true,
    image: 'chocolate-avocado-mousse',
    description: 'A surprisingly rich and creamy chocolate mousse made with healthy avocados. A guilt-free dessert.',
    calories: 250,
    protein: 5,
    carbs: 25,
    fat: 18,
    ingredients: [
      '2 ripe avocados',
      '1/2 cup unsweetened cocoa powder',
      '1/2 cup maple syrup or honey',
      '1/4 cup almond milk',
      '1 tsp vanilla extract',
      'A pinch of salt',
    ],
    instructions: [
      'Combine all ingredients in a blender or food processor.',
      'Blend until completely smooth.',
      'Chill in the refrigerator for at least 30 minutes before serving.',
      'Garnish with berries or mint leaves.',
    ],
  },
   {
    id: 'green-detox-smoothie',
    name: 'Green Detox Smoothie',
    category: 'smoothies',
    isCocktail: false,
    image: 'green-detox-smoothie',
    description: 'A cleansing and nutrient-packed green smoothie with spinach, banana, and pineapple for a tropical twist.',
    calories: 190,
    protein: 5,
    carbs: 40,
    fat: 2,
    ingredients: [
      '1 cup spinach',
      '1/2 frozen banana',
      '1/2 cup pineapple chunks',
      '1/2 cup coconut water',
      '1 tbsp flaxseed',
    ],
    instructions: [
      'Combine all ingredients in a blender.',
      'Blend until smooth and creamy.',
      'Serve immediately for maximum freshness.',
    ],
  },
  {
    id: 'black-bean-burgers',
    name: 'Black Bean Burgers',
    category: 'vegetarian',
    image: 'black-bean-burger',
    description:
      'Hearty, flavorful, and satisfying black bean burgers that are easy to make.',
    calories: 320,
    protein: 15,
    carbs: 45,
    fat: 10,
    ingredients: [
      '1 can (15 oz) black beans, rinsed and mashed',
      '1/2 cup breadcrumbs',
      '1/4 cup chopped onion',
      '1 tsp cumin',
      'Burger buns and toppings',
    ],
    instructions: [
      'Mix black beans, breadcrumbs, onion, and cumin.',
      'Form into patties.',
      'Cook on a lightly oiled pan for 5-7 minutes per side.',
      'Serve on buns with your favorite toppings.',
    ],
  },
  {
    id: 'caprese-salad',
    name: 'Caprese Salad',
    category: 'salads',
    image: 'caprese-salad',
    description:
      'A simple Italian salad, made of sliced fresh mozzarella, tomatoes, and sweet basil.',
    calories: 200,
    protein: 10,
    carbs: 5,
    fat: 15,
    ingredients: [
      '1 ripe tomato, sliced',
      '4 oz fresh mozzarella, sliced',
      'Fresh basil leaves',
      '1 tbsp balsamic glaze',
      '2 tbsp olive oil',
    ],
    instructions: [
      'Arrange tomato and mozzarella slices on a plate.',
      'Top with fresh basil leaves.',
      'Drizzle with olive oil and balsamic glaze.',
    ],
  },
  {
    id: 'chicken-noodle-soup',
    name: 'Chicken Noodle Soup',
    category: 'chicken',
    image: 'chicken-noodle-soup',
    description: 'A classic comfort food, perfect for a cold day.',
    calories: 250,
    protein: 20,
    carbs: 30,
    fat: 5,
    ingredients: [
      '1 cooked chicken breast, shredded',
      '4 cups chicken broth',
      '1 cup egg noodles',
      '1 cup mixed vegetables (carrots, celery)',
    ],
    instructions: [
      'Bring chicken broth to a boil.',
      'Add noodles and vegetables, cook until tender.',
      'Stir in shredded chicken.',
      'Season with salt and pepper.',
    ],
  },
  {
    id: 'cod-with-lemon-dill',
    name: 'Cod with Lemon and Dill',
    category: 'fish-seafood',
    image: 'cod-lemon-dill',
    description: 'A light and flaky cod fish recipe with bright flavors.',
    calories: 280,
    protein: 40,
    carbs: 2,
    fat: 12,
    ingredients: [
      '2 cod fillets',
      '1 lemon, sliced',
      '2 tbsp fresh dill, chopped',
      '1 tbsp olive oil',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Place cod on a baking sheet.',
      'Top with olive oil, lemon slices, and dill.',
      'Bake for 10-12 minutes, or until fish flakes easily.',
    ],
  },
  {
    id: 'cucumber-salad',
    name: 'Cucumber Salad',
    category: 'low-calorie',
    image: 'cucumber-salad',
    description: 'A refreshing, simple salad that is perfect for a summer day.',
    calories: 80,
    protein: 2,
    carbs: 10,
    fat: 4,
    ingredients: [
      '2 cucumbers, thinly sliced',
      '1/4 red onion, thinly sliced',
      '2 tbsp rice vinegar',
      '1 tsp sesame oil',
    ],
    instructions: [
      'Combine cucumbers and red onion in a bowl.',
      'Whisk together rice vinegar and sesame oil.',
      'Pour dressing over cucumbers and toss to coat.',
    ],
  },
  {
    id: 'roasted-broccoli',
    name: 'Roasted Broccoli',
    category: 'vegetable',
    image: 'roasted-broccoli',
    description: 'A simple and delicious way to enjoy broccoli.',
    calories: 100,
    protein: 5,
    carbs: 10,
    fat: 5,
    ingredients: [
      '1 head of broccoli, cut into florets',
      '1 tbsp olive oil',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Toss broccoli with olive oil, salt, and pepper.',
      'Roast for 15-20 minutes, until tender and slightly crispy.',
    ],
  },
  {
    id: 'fruit-parfait',
    name: 'Fruit Parfait',
    category: 'desserts',
    isDessert: true,
    image: 'fruit-parfait',
    description: 'A healthy and beautiful layered dessert.',
    calories: 250,
    protein: 10,
    carbs: 40,
    fat: 5,
    ingredients: [
      '1 cup Greek yogurt',
      '1/2 cup mixed berries',
      '1/4 cup granola',
    ],
    instructions: [
      'Layer yogurt, berries, and granola in a glass.',
      'Repeat layers as desired.',
      'Serve immediately.',
    ],
  },
  {
    id: 'mango-lassi',
    name: 'Mango Lassi Smoothie',
    category: 'smoothies',
    isCocktail: false,
    image: 'mango-lassi',
    description: 'A creamy and refreshing Indian-style smoothie.',
    calories: 280,
    protein: 10,
    carbs: 50,
    fat: 5,
    ingredients: [
      '1 cup chopped ripe mango',
      '1 cup plain yogurt',
      '1/2 cup milk',
      '1 tbsp honey (optional)',
    ],
    instructions: [
      'Combine all ingredients in a blender.',
      'Blend until smooth and creamy.',
      'Pour into a glass and serve chilled.',
    ],
  },
  {
    id: 'spinach-feta-stuffed-chicken',
    name: 'Spinach and Feta Stuffed Chicken',
    category: 'chicken',
    image: 'spinach-feta-chicken',
    description:
      'A flavorful and elegant chicken dish that is surprisingly easy to make.',
    calories: 380,
    protein: 50,
    carbs: 5,
    fat: 18,
    ingredients: [
      '2 chicken breasts',
      '1/2 cup spinach, chopped',
      '1/4 cup feta cheese, crumbled',
      '1 tbsp olive oil',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Cut a pocket into each chicken breast.',
      'Mix spinach and feta, then stuff into chicken.',
      'Sear chicken in an oiled, oven-safe skillet, then bake for 15-20 minutes.',
    ],
  },
  {
    id: 'tuna-salad',
    name: 'Tuna Salad',
    category: 'fish-seafood',
    image: 'tuna-salad',
    description: 'A classic, simple, and protein-packed salad.',
    calories: 220,
    protein: 25,
    carbs: 2,
    fat: 12,
    ingredients: [
      '1 can (5 oz) tuna, drained',
      '1/4 cup mayonnaise or Greek yogurt',
      '1 celery stalk, finely chopped',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Combine all ingredients in a bowl.',
      'Mix until well combined.',
      'Serve on bread, crackers, or a bed of lettuce.',
    ],
  },
  {
    id: 'egg-drop-soup',
    name: 'Egg Drop Soup',
    category: 'low-calorie',
    image: 'egg-drop-soup',
    description: 'A light, comforting, and easy-to-make Chinese soup.',
    calories: 90,
    protein: 8,
    carbs: 5,
    fat: 4,
    ingredients: [
      '4 cups chicken broth',
      '1 egg, beaten',
      '1 tbsp cornstarch',
      '1 green onion, chopped',
    ],
    instructions: [
      'Bring broth to a simmer.',
      'Whisk cornstarch with 2 tbsp of cold water and stir into broth.',
      'Slowly pour in the beaten egg while stirring the soup.',
      'Garnish with green onion.',
    ],
  },
  {
    id: 'stuffed-bell-peppers',
    name: 'Stuffed Bell Peppers',
    category: 'vegetable',
    image: 'stuffed-peppers',
    description:
      'A versatile and colorful dish that can be filled with anything you like.',
    calories: 300,
    protein: 15,
    carbs: 35,
    fat: 10,
    ingredients: [
      '2 bell peppers, halved and seeded',
      '1 cup cooked rice',
      '1/2 cup black beans',
      '1/2 cup corn',
      '1/4 cup shredded cheese',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Mix rice, beans, corn, and cheese.',
      'Stuff mixture into bell pepper halves.',
      'Bake for 20-25 minutes, until peppers are tender.',
    ],
  },
  {
    id: 'baked-apple',
    name: 'Baked Apple',
    category: 'desserts',
    isDessert: true,
    image: 'baked-apple',
    description: 'A simple, warm, and comforting dessert.',
    calories: 150,
    protein: 1,
    carbs: 40,
    fat: 0,
    ingredients: [
      '1 apple',
      '1 tbsp brown sugar',
      '1/2 tsp cinnamon',
      '1 tbsp oats',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Core the apple and place it in a baking dish.',
      'Mix brown sugar, cinnamon, and oats, and fill the apple.',
      'Bake for 20-30 minutes, until apple is tender.',
    ],
  },
  {
    id: 'peanut-butter-banana-smoothie',
    name: 'Peanut Butter Banana Smoothie',
    category: 'smoothies',
    isCocktail: false,
    image: 'peanut-butter-smoothie',
    description: 'A creamy, protein-packed smoothie that tastes like a treat.',
    calories: 350,
    protein: 15,
    carbs: 40,
    fat: 15,
    ingredients: [
      '1 frozen banana',
      '2 tbsp peanut butter',
      '1 cup milk of choice',
      '1 scoop protein powder (optional)',
    ],
    instructions: [
      'Combine all ingredients in a blender.',
      'Blend until smooth and creamy.',
      'Pour into a glass and enjoy.',
    ],
  },
  {
    id: 'strawberry-spinach-salad',
    name: 'Strawberry Spinach Salad',
    category: 'salads',
    image: 'strawberry-spinach-salad',
    description: 'A sweet and savory salad perfect for spring and summer.',
    calories: 250,
    protein: 8,
    carbs: 20,
    fat: 15,
    ingredients: [
      '4 cups spinach',
      '1 cup sliced strawberries',
      '1/4 cup crumbled goat cheese',
      '1/4 cup toasted almonds',
      'Balsamic vinaigrette dressing',
    ],
    instructions: [
      'Combine spinach, strawberries, goat cheese, and almonds in a large bowl.',
      'Drizzle with balsamic vinaigrette just before serving.',
      'Toss gently to combine.',
    ],
  },
  {
    id: 'sheet-pan-chicken-fajitas',
    name: 'Sheet Pan Chicken Fajitas',
    category: 'chicken',
    image: 'sheet-pan-fajitas',
    description: 'An easy one-pan dinner with all the flavors of fajitas.',
    calories: 400,
    protein: 35,
    carbs: 25,
    fat: 18,
    ingredients: [
      '1 lb chicken breast, sliced',
      '2 bell peppers, sliced',
      '1 onion, sliced',
      '1 packet fajita seasoning',
      'Flour tortillas for serving',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Toss chicken, peppers, and onion with fajita seasoning on a baking sheet.',
      'Bake for 20-25 minutes, until chicken is cooked through.',
      'Serve with warm tortillas.',
    ],
  },
  {
    id: 'shrimp-and-avocado-ceviche',
    name: 'Shrimp and Avocado Ceviche',
    category: 'fish-seafood',
    image: 'shrimp-ceviche',
    description: 'A refreshing and zesty appetizer or light meal.',
    calories: 280,
    protein: 20,
    carbs: 15,
    fat: 15,
    ingredients: [
      '1 lb cooked shrimp, chopped',
      '1 avocado, diced',
      '1/2 red onion, finely chopped',
      '1 jalapeno, minced',
      '1/2 cup lime juice',
      '1/4 cup chopped cilantro',
    ],
    instructions: [
      'Combine all ingredients in a bowl.',
      'Let it marinate in the refrigerator for at least 30 minutes.',
      'Serve chilled with tortilla chips.',
    ],
  },
  {
    id: 'zucchini-fritters',
    name: 'Zucchini Fritters',
    category: 'low-calorie',
    image: 'zucchini-fritters',
    description:
      'A light and healthy way to use up summer zucchini. Great as a snack or side dish.',
    calories: 150,
    protein: 8,
    carbs: 15,
    fat: 6,
    ingredients: [
      '2 cups grated zucchini',
      '1 egg',
      '1/4 cup flour',
      '1/4 cup grated Parmesan cheese',
    ],
    instructions: [
      'Squeeze excess water from zucchini.',
      'Mix zucchini with egg, flour, and Parmesan.',
      'Form into small patties and pan-fry until golden brown.',
    ],
  },
  {
    id: 'roasted-brussels-sprouts',
    name: 'Roasted Brussels Sprouts',
    category: 'vegetable',
    image: 'roasted-brussels-sprouts',
    description: 'Crispy, caramelized, and irresistibly delicious.',
    calories: 130,
    protein: 6,
    carbs: 15,
    fat: 6,
    ingredients: [
      '1 lb brussels sprouts, trimmed and halved',
      '1 tbsp olive oil',
      'Balsamic glaze for drizzling',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Toss brussels sprouts with olive oil, salt, and pepper.',
      'Roast for 20-25 minutes, until crispy.',
      'Drizzle with balsamic glaze before serving.',
    ],
  }
];

export const getRecipes = () => allRecipes;

export const getRecipeById = (id: string) =>
  allRecipes.find((recipe) => recipe.id === id);

export const getRecipesByCategory = (categorySlug: string) =>
  allRecipes.filter((recipe) => recipe.category === categorySlug);

export const getFeaturedRecipes = (count: number) => {
  const shuffled = [...allRecipes].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
